language: node_js
node_js:
  - "node"
before_script:
  - npm i app
script:
  - cd app; npm run build-site
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: app/dist
  on:
    branch: master
