language: node_js
node_js:
  - "10"
install:
  - yarn global add lerna jest
  - yarn
  - lerna bootstrap
script:
  - yarn test
  - mkdir app/dist
  - git worktree add app/dist/ gh-pages
  - yarn build-site
  - cd app/dist/
  - git status
